### ISSUE TITLE
【タイムテーブル】セッションのジャンル分けについて

### ISSUE THREAD

**Issue by lunaluna** [wct2019/website#119]
- セッションに「デザイナー向け」「エンジニア向け」などのカテゴリを付与する？
- カテゴリごとに背景色（または背景の柄）を変えておくとタイムラインのイメージが湧きやすい
- パンフ、場内の案内ではやるとしてサイト内のタイムテーブルでやるかどうか

**Comment by atrasi2079** [comment]
@lunaluna 
背景色でカテゴリ分けをするのは、既にトラックごとに背景色を分けていますので、色情報が前に出すぎてしまってかえって分かりにくくなる事が予想されます。

手法としてはちょっと地道ですが、2017のタイムテーブルの様に擬似要素等を駆使して各ジャンルごとの記載をタイトルの近くに配置するのが良いのではないかと思います。
https://2017.tokyo.wordcamp.org/schedule/#schedule-session-day

**Comment by lunaluna** [comment]
承知です！必要であればセッション班と連携してうまくカテゴリ分けができるといいと思います！

**Comment by atrasi2079** [comment]
@lunaluna 
そうですね。まずセッション班と相談して、まだカテゴリ分けが出来ていないのであればカテゴリ分けが出来てから順次対応って感じですね。

**Comment by hudsoncliff** [comment]
タイムテーブルのジャンルわけ
デザイン：#cc0000
エンジニア：#0000cc
ディレクター：#009900
ブロガー：#ff6600
英語：#bb00ee
