### ISSUE TITLE
In-Kindスポンサーのレイアウト崩れ

### ISSUE THREAD

**Issue by lunaluna** [wct2019/website#127]
![スクリーンショット 2019-09-18 13 01 48](https://user-images.githubusercontent.com/1078657/65110972-2ca9ba80-da15-11e9-82f4-8ae18c965284.png)

![スクリーンショット 2019-09-18 13 05 33](https://user-images.githubusercontent.com/1078657/65110980-32070500-da15-11e9-9833-43196f0c36ea.png)

In-Kindスポンサーを2件にしたところ、ブロック間のmarginが当たっていませんでした。

**Comment by atrasi2079** [comment]
当初、一件のみの前提でここだけCSSが異なっているので、後ほど調整します。

既にスポンサー募集は終了していますが、今後in Kindが増えない前提なのか、まだ増える可能性があるのかで修正の方向性を考えようかなと思います。その辺どうでしょう？

**Comment by lunaluna** [comment]
これ以上In-Kindスポンサーが増える予定はありません、遅くまで対応ありがとうございました！！
