### ISSUE TITLE
スマホ版はナビゲーションのホームを家アイコンにしたい

### ISSUE THREAD

**Issue by atrasi2079** [wct2019/website#130]
現状、スマホ版のメニューは元になったテーマの仕様で項目が先頭3つほどしかされず、後は三点リーダアイコンに集約されます。

表示項目数を増やす目的で、スマホ版の時だけナビゲーションメニュー先頭にあるホームを家アイコンにするのを検討してみようと思います。
ただ、これによって果たしてスマホ版のメニュー領域が広がって表示項目が増えるとは限りません(JSも絡んでいるため)。そのため、検証してみた結果、期待通りの挙動にならなければ実装は見送りたいと思います。

**Comment by hudsoncliff** [comment]
@atrasi2079 

![wct2019 local_(iPhone 6_7_8)](https://user-images.githubusercontent.com/1096023/65329911-6e448c00-dbf4-11e9-8c20-8038d2211825.png)

ローカルで試したら、こんなかんじでした！
幅を極限まで小さくしても（0pxでも）表示領域は増えなかったです。

**Comment by atrasi2079** [comment]
@hudsoncliff 
検証ありがとうございます！
おおお…無念…。やはりと言いますか、JS処理が微妙に入っているせいもあるんですかね…。思ったとおりにはならなそうですね。


@shusei-t 
先日あったHomeをスマホ版でアイコンにする案ですが、残念ながら表示項目数を増やすことは出来ないっぽいです…。

**Comment by shusei-t** [comment]
残念...
承知いたしました。
小野さん、検証するのに時間割いてくださりありがとうございました。

が、悔しいですが、この案はお蔵入りということにさせてください。
