### ISSUE TITLE
トップページ 最新情報のタイトルが長すぎる場合、日付が折り返してしまっている

### ISSUE THREAD

**Issue by kutsu123** [wct2019/website#132]
PCにて、記事のタイトルが長い場合、トップページの最新情報のタイトル部分にて、日付が折り返してしまっています。
タイトルが長い場合、日付は次の行にするか折り返さないようにしたほうが見やすいかなと思いました。

※情報が読み取れないわけではないので、余力があったら直していただけるというレベルでいい気がします

**Comment by atrasi2079** [comment]
ご指摘ありがとうございます！

メモ
.front-news ul li .wp-block-latest-posts__post-date
にwidthを指定する(PCだと150px)で対処

**Comment by atrasi2079** [comment]
@hudsoncliff 
すいません、こちら対応お願いできますでしょうか？
