### ISSUE TITLE
【タイムテーブル】スマホ時のカテゴリ表示の調整

### ISSUE THREAD

**Issue by lunaluna** [wct2019/website#134]
![スクリーンショット-2019-09-26-11 54 07](https://user-images.githubusercontent.com/1078657/65654659-8c771580-e054-11e9-8531-9b7d7f61136d.png)

スマホでタイムテーブルを表示した際に、カテゴリーの表示部分を
・セッションタイトル、「Speaker」と左を揃えたい
・「Speaker」との間隔をとりたい
（添付画像の「井水さん」参照のこと）

**Comment by atrasi2079** [comment]
@hudsoncliff 
すいません！こちら対応して頂いていいですか？

**Comment by hudsoncliff** [comment]
@atrasi2079 
了解しました！
