### ISSUE TITLE
【優先度低】カテゴリのないセッション

### ISSUE THREAD

**Issue by lunaluna** [wct2019/website#135]
カテゴリは任意で追加できたでしょうか？
いまあるカテゴリとは別に、例えば「共通」「オールジャンル」のようなカテゴリを用意して、タイムテーブル上でカテゴリが表示されていないセッションにカテゴリづけしたいです。

**Comment by atrasi2079** [comment]
共通カテゴリですが、既にタイムテーブル上に各カテゴリの色分けもしてあってカラーパレット的にもかなり色が多い状態になっています。
また、共通・オールジャンルというのは、◎◎向きというどの傾向にも属さないので共通に関しては今回カテゴリ表示は対応しない予定です。
ご了承宜しくお願い致します。

**Comment by lunaluna** [comment]
承知いたしました、ありがとうございます。
