### ISSUE TITLE
チケットスタイル作成

### ISSUE THREAD

**Issue by hudsoncliff** [wct2019/website#14]
チケット購入とチケットを購入した参加者一覧のショートコード
[camptix][camptix_attendees]

**Comment by atrasi2079** [comment]
@hudsoncliff 
ローカル環境の管理画面にチケットメニューが無いということは、これだけもしかすると別プラグインの可能性ありかも…？

**Comment by hudsoncliff** [comment]
@atrasi2079 
そうですね！
確か、ドキュメントにはチケット用のプラグインのことが書いてあったので、ちょっとみてみます！

**Comment by hudsoncliff** [comment]
@atrasi2079 
チケットですが、下記リンクのプラグインを有効化するとチケットの投稿タイプが有効になりましたので、ご確認ください。
適当なチケットを作成して、メニューの「チケット→設定」で決済方法を有効にするとショートコードが表示されるかと思います。
https://ja.wordpress.org/plugins/camptix/

**Comment by atrasi2079** [comment]
@hudsoncliff 
ありがとうございます！
明日にでも試してみます！
