### ISSUE TITLE
実行委員リストの作成

### ISSUE THREAD

**Issue by miminari** [wct2019/website#54]
related #2

実行委員の一覧ページを作成中です。
https://2019.tokyo.wordcamp.org/?page_id=12&preview=true

ショートコードだと、タグ構成が微妙（名前がh2タグ固定）なので困ったな、と。

でご相談なのですが、こちらのベータ版のWordCamp用のブロックだとタグ構成がきれいみたいです。
https://make.wordpress.org/community/2019/05/29/who-wants-to-test-the-new-wordcamp-blocks/

参考ページ:
https://2020.asia.wordcamp.org/organisers/

こちら、ベータ版の有効化リクエストをすれば使えるようになるそうなのですが、どう思われますか？ご検討ください。

**Comment by atrasi2079** [comment]
正直、HTMLタグ構成に関しては気持ち悪いところはあるんですが、一部ページでウィジェットをdisplay:noneしてるくらいなので、そこまで重視しなくても良いかなと思っています。β版のブロックに合わせて再構成するコストと、現在までに入れた実行委員会用CSSの改修コストと天秤にかけた場合に、どうしてもβ版ブロックである必要性があるのであれば検討するんですが、単に見栄えの問題なのであれば今のショートコードの方でも良いかなと。

最終的に実行委員会一覧でどういう情報を出したいのかで決まってくると思います。
直近の2018・2017のWordCampTokyoサイトを見る限り実行委員会の一覧自体がなく、マイクロスポンサー一覧の様に顔アイコン+名前程度かなと思っていたのですが、全ての方に紹介文とSNSリンクを貼るという方向で考えているということでしょうか。紹介文などを入れるとなると、CSSの調整もそうですが各人から自己紹介文も集めないとならないでしょうし、その辺も含めて検討する必要があると思います。
なので、まずは着地点を決めたほうが良いんじゃないかと思います。

**Comment by miminari** [comment]
早速ご回答ありがとうございます！了解です。

**β版導入**
- β版導入対応のコストの方が高いので、導入は見送りましょう。タグ構成は無視でOKです！

**実行委員一覧**
- 実行委員一覧は、近年のTokyoがイレギュラーだったようで作成するのが一般的です。
https://2017.kyoto.wordcamp.org/organizers/
https://2018.osaka.wordcamp.org/organizers/
https://2018.ogijima.wordcamp.org/organizers/
- （個人的には、どっちでも良いと思っていますが）チーム感を出すためにもモチベーションを上げるためにもあったほうが良いのではという意見があります。
- どうせ作るなら紹介文があるほうが良いと思います。SNSや個人ブログなどのリンクも可です。長過ぎるものは編集しましょう。掲載可否は各実行委員の任意で、編集者権限でアカウントを発行して記載は本人に任せる形となるかと思います。
- 特に、2カラムとかにしなくても良いと思います。なるべく負担の無い形で！

**Comment by miminari** [comment]
すいません、肝心なことを書き忘れました。
この件は9月以降で良いのでそんなに急ぎません！

**Comment by atrasi2079** [comment]
早速の返信、ありがとうございます！了解です！
では、紹介文が入った状態でCSSを当てていきたいので、オーガナイザーチームの方の紹介文をいくつか登録しておいてもらえると助かります〜！
