### ISSUE TITLE
タイムテーブルのCSSの調整

### ISSUE THREAD

**Issue by atrasi2079** [wct2019/website#57]
セッション班・会場班からセッションデイの詳細なタイムテーブルが出たら、CSSを調整する

**Comment by atrasi2079** [comment]
@hudsoncliff 

会場案内・タイムテーブルのアイコンと色が決まりました！
制作時は以下をベースにして下さい。現在あるCSSは私が作ったものですので、変更しちゃってOKです。必要に応じて変数にしちゃってもOKです。


◎セッションルーム
ダイヤモンド Diamond (Room AB)
＃4DAE81
C68 M7 Y6 K0

クローバー Clover (Room CD)
＃5B9EB7
C65 M25 Y22 K0

ハート Heart (Room GH)
＃E16E7F
C3 M68 Y31 K5

スペード Spade (Room K)
＃A180A2
C24 M43 Y0 K28

◎スポンサーブース
太陽 Sun (Room EF)
＃F39E5F
C0 M48 Y63 K0

◎その他
月 Moon (Room J)
休憩スペース

星 Star (Room I)
交流ルーム

旗 Flag (Lobby & Reception)
ロビー・本部受付



aiデータ
https://drive.google.com/drive/folders/1010Xsej39Cdp25jeL-kQQr5wfNjVHFCV?usp=sharing

![room_icon_color](https://user-images.githubusercontent.com/1813575/64244022-47732e00-cf43-11e9-8ed6-13ebeaea2318.jpg)

**Comment by hudsoncliff** [comment]
@atrasi2079 
了解しました！

**Comment by atrasi2079** [comment]
@hudsoncliff 
お待たせ致しました！
セッション班からタイムテーブルの知らせがきました。

https://docs.google.com/spreadsheets/d/1VWEx_M4mqs0MIe4xxcwYqXVE3mi4exgcJqz1GYJ6_PE/edit?usp=sharing

上記スプレッドシートの「サイト向け」というシートをご確認下さい。(確定というシートは内部向けだそうです)

本サイトのセッション情報の入力は、セッション班・委員長ズの方で今夜を目処に行ってくれるそうですので、ローカルへのインポートや実際のCSS調整はその後で大丈夫だと思います。

一応、様子だけお手すきの際にでもご確認下さいませ！

**Comment by hudsoncliff** [comment]
@atrasi2079 
了解しました！
補足諸々ありがとうございます

連休中のコミットを目指して作業とりかかります！
