### ISSUE TITLE
トップページの構成を変更

### ISSUE THREAD

**Issue by atrasi2079** [wct2019/website#68]
トップページの構成を、現在の新しい投稿を見せるスタイルから専用の固定ページに設定する。
構成は現在思案中。

https://docs.google.com/document/d/1My78UZIlk79yZtQ2XyzpRhvIyGOReSikfkrN4OHg3W0/edit?usp=sharing

**Comment by atrasi2079** [comment]
構成とデザインベース
https://www.figma.com/file/zlhUbTVs2bqoNCWDxjDcvT/wct2019-top-wire?node-id=0%3A1

**Comment by shusei-t** [comment]
作成ありがとうございます。
全体的に問題はないのですが、視認性の関係で改行とかがあるといいかもなー
って思ったところをデベロッパーモードで作ってみました。
今のままでOKなのですが、検討する余地があればぜひにm(_ _)m
<img width="487" alt="スクリーンショット 2019-09-03 1 59 00" src="https://user-images.githubusercontent.com/53067918/64127906-b0955d00-cdee-11e9-9be1-20ad9a606f7e.png">
<img width="481" alt="スクリーンショット 2019-09-03 1 59 10" src="https://user-images.githubusercontent.com/53067918/64127909-b3904d80-cdee-11e9-987c-6ba5f69dc6f6.png">
<img width="477" alt="スクリーンショット 2019-09-03 1 59 19" src="https://user-images.githubusercontent.com/53067918/64127910-b4c17a80-cdee-11e9-9962-52f90aa50e0a.png">

**Comment by atrasi2079** [comment]
たしかに。
参加費と日程を横並びにするより、参加費と日程を縦に分けて書いたほうがもしかしてわかりやすいかもですね。ちょっと試してみます。

あとスマホで微妙な部分があったのと、なぜかブロックの順番が入れ替わってしまった箇所があったので後日修正しておきます！
