### ISSUE TITLE
デジタルガチャの背景とボタンデザイン

### ISSUE THREAD

**Issue by miminari** [wct2019/website#73]
スタンプラリーとアンケートの景品ガチャを今年も使います。
ソースは去年のものを流用して、
背景画像とボタンデザインを作成してください。
（各種ノベルティの絵も入れ替え必要）

https://github.com/wct2018/slot

**Comment by atrasi2079** [comment]
@miminari 
ちょっとお伺いしたいのですが、このルーレットって例年どうやって運用していたかわかりますか？
本部受付にPC等を置いて、そのPCのローカル環境下で動かしていたのでしょうか？それとも何かしらの仮サーバを使っていたのでしょうか？

それと在庫量をJSファイルを直接いじって…とお伺いしましたが、当日JSをいじれる人員を配置しておくという事になると思うんですけど、当日班の方で吸収できるのかどうかちょっと懸念しています。

そのへんの詳細が知りたいので、宜しくお願い致します〜！

**Comment by miminari** [comment]
ああ、たしかに！
去年は、これをどこでやってたかぐらいしか記憶がないです。すみません。
去年のガチャの詳細がわかりそうな人にヒアリングしてみますね！

**Comment by miminari** [comment]
https://github.com/wct2019/roulette
mukkuさんが作ってくれたこっちのレポジトリで続きを相談いたしましょうー！
