### ISSUE TITLE
登壇者スタイル作成

### ISSUE THREAD

**Issue by hudsoncliff** [wct2019/website#9]
ショートコード名: speakers

**Comment by atrasi2079** [comment]
@0serika0 
とりあえず、こちらのタスクだけお願いします。
余裕ありそうでしたら他タスクもお願いしますので、ご連絡下さい〜！

**Comment by atrasi2079** [comment]
@0serika0 
進捗いかがでしょうか？もし何か難しそうなところがあれば、お気軽にご相談下さい〜！

**Comment by atrasi2079** [comment]
@0serika0 
その後、進捗の方はいかがでしょうか？
もし稼働難しそうでしたら、Slackの方等でも構いませんのでご連絡下さい！
